import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { resend } from '@/lib/resend'
import { EMAIL_LOGO_SVG } from '@/lib/email-logo'

type AgendaItem = {
  text: string
  owner: string | null
  urgency: 'high' | 'medium' | 'low' | null
  note: string | null
}

type AgendaSection = {
  heading: string
  items: AgendaItem[]
}

type AgendaContent = {
  title: string
  date: string
  summary: string
  sections: AgendaSection[]
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function buildAgendaEmail(content: AgendaContent, ownerName: string): string {
  const sectionsHtml = content.sections
    .map((section) => {
      const itemsHtml = section.items
        .map((item) => {
          const borderColor =
            item.urgency === 'high'
              ? '#ef4444'
              : item.urgency === 'medium'
              ? '#f59e0b'
              : 'transparent'
          const bgColor =
            item.urgency === 'high'
              ? '#fff1f2'
              : item.urgency === 'medium'
              ? '#fffbeb'
              : '#f9fafb'

          const ownerBadge = item.owner
            ? `<span style="background:#e5e7eb;color:#374151;font-size:11px;padding:2px 8px;border-radius:3px;margin-left:8px;">${escapeHtml(item.owner)}</span>`
            : ''

          const urgencyBadge =
            item.urgency && item.urgency !== 'low'
              ? `<span style="background:${item.urgency === 'high' ? '#fee2e2' : '#fef3c7'};color:${item.urgency === 'high' ? '#b91c1c' : '#92400e'};font-size:11px;padding:2px 8px;border-radius:3px;margin-left:8px;">${escapeHtml(item.urgency)}</span>`
              : ''

          const note = item.note
            ? `<p style="color:#6b7280;font-size:12px;margin:4px 0 0;font-style:italic;">${escapeHtml(item.note)}</p>`
            : ''

          return `<div style="padding:10px 12px;margin:0 0 6px;border-radius:4px;border-left:3px solid ${borderColor};background:${bgColor};">
  <div><span style="color:#111827;font-size:14px;">${escapeHtml(item.text)}</span>${ownerBadge}${urgencyBadge}</div>${note}
</div>`
        })
        .join('')

      return `<div>
  <h3 style="color:#111827;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.05em;margin:24px 0 12px;border-bottom:1px solid #e5e7eb;padding-bottom:8px;">${escapeHtml(section.heading)}</h3>
  ${itemsHtml}
</div>`
    })
    .join('')

  const summaryHtml = content.summary
    ? `<div style="color:#374151;font-size:15px;line-height:1.7;background:#f9fafb;padding:16px;border-radius:6px;margin:0 0 24px;">${escapeHtml(content.summary)}</div>`
    : ''

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8">
<style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f3f4f6;margin:0;padding:0;}</style>
</head>
<body>
<div style="max-width:600px;margin:0 auto;background:#ffffff;">
  <div style="background:#ffffff;padding:32px 40px;border-bottom:2px solid #22d45f;text-align:center;">${EMAIL_LOGO_SVG}</div>
  <div style="background:#ffffff;padding:36px 40px;">
    <h1 style="color:#111827;font-size:22px;font-weight:bold;margin:0 0 4px;">${escapeHtml(content.title)}</h1>
    <p style="color:#6b7280;font-size:14px;margin:0 0 20px;">${escapeHtml(content.date)}</p>
    ${summaryHtml}
    ${sectionsHtml}
  </div>
  <div style="background:#f9fafb;padding:20px 40px;border-top:1px solid #e5e7eb;">
    <p style="color:#9ca3af;font-size:11px;margin:0;line-height:1.6;">Agenda generated by Arlo on behalf of ${escapeHtml(ownerName)}.</p>
  </div>
</div>
</body>
</html>`
}

export async function POST(request: Request) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { agendaId, attendeeEmails } = await request.json()
  if (!agendaId || !attendeeEmails?.length) {
    return NextResponse.json({ error: 'agendaId and attendeeEmails are required' }, { status: 400 })
  }

  const { data: agenda, error: fetchError } = await supabaseAdmin
    .from('agendas')
    .select('*')
    .eq('id', agendaId)
    .eq('owner_id', user.id)
    .single()

  if (fetchError || !agenda) {
    return NextResponse.json({ error: 'Agenda not found' }, { status: 404 })
  }

  const { data: profile } = await supabaseAdmin
    .from('profiles')
    .select('display_name')
    .eq('id', user.id)
    .maybeSingle()

  const ownerName = profile?.display_name || user.email || 'Owner'
  const content = agenda.content as AgendaContent

  const html = buildAgendaEmail(content, ownerName)
  const subject = `Agenda — ${content.title} — ${content.date}`

  await resend.emails.send({
    from: 'Arlo <arlo@agent-arlo.com>',
    to: attendeeEmails,
    subject,
    html,
  })

  const now = new Date().toISOString()
  const { data: updated, error: updateError } = await supabaseAdmin
    .from('agendas')
    .update({ sent_at: now, sent_to: attendeeEmails })
    .eq('id', agendaId)
    .select()
    .single()

  if (updateError) return NextResponse.json({ error: updateError.message }, { status: 500 })

  return NextResponse.json(updated)
}
